---
- name: "Install apache2"
  become: true
#  apt:
  homebrew:
    name: ["apache"]
    state: latest
    update_cache: yes

- name: "Install index page"
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes